on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
      - name: Install dependencies
        runs: yarn --frozen-lockfile
      - name: Build the files
        runs: yarn build
      - name: Deploy to GitHub pages
        runs: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore(ci): Deploy to GitHub pages"
          git subtree push --prefix dist origin gh-pages
