on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
      - name: Install dependencies
        runs: yarn --frozen-lockfile
      - name: Build the files
        runs: yarn build
